# Generated by Django 3.2.4 on 2021-10-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('phone', models.IntegerField(max_length=12)),
                ('subject', models.CharField(max_length=350)),
                ('message', models.TextField()),
            ],
        ),
    ]
